name: 'Set up Eldev'
description: 'Install Eldev for testing Elisp projects.'
author: 'doublep'

runs:
  using: composite
  steps:
  - if: runner.os != 'Windows'
    run: curl -fsSL https://raw.github.com/emacs-eldev/eldev/master/webinstall/github-eldev | sh
    shell: bash
  - if: runner.os == 'Windows'
    run: curl.exe -fsSL https://raw.github.com/emacs-eldev/eldev/master/webinstall/github-eldev.bat | cmd /Q
    shell: pwsh

# https://haya14busa.github.io/github-action-brandings
branding:
  icon: 'command'
  color: 'orange'
