name: CI

on:
  push:
    paths-ignore: ['**.md', '**.adoc']
  pull_request:
    paths-ignore: ['**.md', '**.adoc']

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # FIXME: Or test on different Emacs versions?  Probably not needed.
        emacs_version: ['29.1']

    steps:
    - name: Set up Emacs
      uses: jcs090218/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Check out the source code
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

    - name: Execute ourselves
      uses: ./

    - name: Verify that Eldev is now available
      run: |
        eldev version eldev emacs
